# Generated by Django 4.1.7 on 2023-02-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='theme',
            field=models.CharField(default='', max_length=100, verbose_name='Tema'),
        ),
    ]
