# Generated by Django 4.1.7 on 2023-02-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='theme',
            field=models.CharField(max_length=100, verbose_name='Tema'),
        ),
    ]
