# Generated by Django 4.1.7 on 2023-03-09 21:10

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.FileField(upload_to=items.models.File.get_file_path, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=items.models.Image.get_file_path, verbose_name='imagen'),
        ),
    ]
