# Generated by Django 4.1.7 on 2023-04-01 18:53

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_file_filename_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to=items.models.Theme.get_file_path, verbose_name='Imagen tema')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.FileField(upload_to=items.models.File.get_file_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=items.models.Image.get_file_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='item',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.theme'),
        ),
    ]
